[programs.localnet]
openpacksduel_escrow = "Co198eFfQcmn1WzZRnHV6jxcSLBDCv1qNfPfiBYdCLfS"

[programs.devnet]
openpacksduel_escrow = "Co198eFfQcmn1WzZRnHV6jxcSLBDCv1qNfPfiBYdCLfS"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
